### PR TITLE
Lab 2

### PR DESCRIPTION
**Pull request by hxnchar**

### CODE REVIEW

**Comment by hxnchar** [comment]
### Deployed at https://modern-nodejs-labs.vercel.app
> Available paths:
`GET`/`DELETE`: https://modern-nodejs-labs.vercel.app/api/joke/
`POST`/`GET`/`DELETE`: https://modern-nodejs-labs.vercel.app/api/joke/skeleton
`GET`: https://modern-nodejs-labs.vercel.app/api/joke/prikol

**Comment by hxnchar** [comment]
IMAGE 2022-11-23 18:33:59
IMAGE 2022-11-23 18:34:08
IMAGE 2022-11-23 18:34:14
IMAGE 2022-11-23 18:34:18

**Comment by hxnchar** [comment]
### Deployed at https://modern-nodejs-labs.vercel.app
> Available paths:
`GET`/`DELETE`: https://modern-nodejs-labs.vercel.app/api/joke/
`POST`/`GET`/`DELETE`: https://modern-nodejs-labs.vercel.app/api/joke/skeleton
`GET`: https://modern-nodejs-labs.vercel.app/api/joke/prikol
### Work examples with different content-types  are on screenshots above

**Comment by nosovk** [comment]
merge

**Pull request merged**
